CREATE OR REPLACE PROCEDURE RESTORE_STUDENTS_STATE(
    target_time TIMESTAMP,
    time_offset NUMBER DEFAULT NULL
) AS
BEGIN
    DELETE FROM STUDENTS;

    INSERT INTO STUDENTS (ID, NAME, GROUP_ID)
    SELECT STUDENT_ID, NEW_NAME, NEW_GROUP_ID
    FROM STUDENTS_LOG
    WHERE ACTION = 'INSERT'
      AND ACTION_TIMESTAMP <= NVL(target_time - NUMTODSINTERVAL(time_offset, 'SECOND'), target_time);

    FOR upd_rec IN (
        SELECT * FROM STUDENTS_LOG
        WHERE ACTION = 'UPDATE'
          AND ACTION_TIMESTAMP <= NVL(target_time - NUMTODSINTERVAL(time_offset, 'SECOND'), target_time)
        ORDER BY ACTION_TIMESTAMP
    ) LOOP
        UPDATE STUDENTS
        SET NAME = upd_rec.NEW_NAME,
            GROUP_ID = upd_rec.NEW_GROUP_ID
        WHERE ID = upd_rec.STUDENT_ID;
    END LOOP;

    DELETE FROM STUDENTS
    WHERE ID IN (
        SELECT STUDENT_ID
        FROM STUDENTS_LOG
        WHERE ACTION = 'DELETE'
          AND ACTION_TIMESTAMP <= NVL(target_time - NUMTODSINTERVAL(time_offset, 'SECOND'), target_time)
    );
END;

-- INSERT INTO STUDENTS_LOG (STUDENT_ID, ACTION, ACTION_TIMESTAMP, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
-- VALUES (1, 'INSERT', SYSTIMESTAMP - INTERVAL '5' MINUTE, NULL, 'Alice', NULL, 101);

-- INSERT INTO STUDENTS_LOG (STUDENT_ID, ACTION, ACTION_TIMESTAMP, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
-- VALUES (2, 'INSERT', SYSTIMESTAMP - INTERVAL '4' MINUTE, NULL, 'Bob', NULL, 102);

-- INSERT INTO STUDENTS_LOG (STUDENT_ID, ACTION, ACTION_TIMESTAMP, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
-- VALUES (1, 'UPDATE', SYSTIMESTAMP - INTERVAL '3' MINUTE, 'Alice', 'Alice Smith', 101, 201);

-- INSERT INTO STUDENTS_LOG (STUDENT_ID, ACTION, ACTION_TIMESTAMP, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
-- VALUES (2, 'UPDATE', SYSTIMESTAMP - INTERVAL '2' MINUTE, 'Bob', 'Bob Brown', 102, 202);

-- INSERT INTO STUDENTS_LOG (STUDENT_ID, ACTION, ACTION_TIMESTAMP, OLD_NAME, NEW_NAME, OLD_GROUP_ID, NEW_GROUP_ID)
-- VALUES (1, 'DELETE', SYSTIMESTAMP - INTERVAL '1' MINUTE, 'Alice Smith', NULL, 201, NULL);


-- BEGIN
--     RESTORE_STUDENTS(SYSTIMESTAMP, NULL);
-- END; 
-- /

