CREATE OR REPLACE TRIGGER trg_update_group_cval
AFTER INSERT OR UPDATE OR DELETE ON STUDENTS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE GROUPS
        SET C_VAL = C_VAL + 1
        WHERE ID = :NEW.GROUP_ID;

    ELSIF UPDATING THEN
        IF :OLD.GROUP_ID != :NEW.GROUP_ID THEN
            UPDATE GROUPS
            SET C_VAL = C_VAL - 1
            WHERE ID = :OLD.GROUP_ID;

            UPDATE GROUPS
            SET C_VAL = C_VAL + 1
            WHERE ID = :NEW.GROUP_ID;
        END IF;

    ELSIF DELETING THEN
        UPDATE GROUPS
        SET C_VAL = C_VAL - 1
        WHERE ID = :OLD.GROUP_ID;
    END IF;
END;


-- BEGIN
--     DELETE FROM STUDENTS;
--     DELETE FROM GROUPS;
--     COMMIT;
-- END;


-- BEGIN
--     INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (1, 'Group A', 0);
--     INSERT INTO GROUPS (ID, NAME, C_VAL) VALUES (2, 'Group B', 0);
--     COMMIT;
-- END;


-- BEGIN
--     INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (1, 'Alice', 1);
--     INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (2, 'Bob', 1);
--     INSERT INTO STUDENTS (ID, NAME, GROUP_ID) VALUES (3, 'Charlie', 2);
--     COMMIT;
-- END;


-- BEGIN
--     UPDATE STUDENTS SET GROUP_ID = 2 WHERE ID = 1;
--     COMMIT;
-- END;


-- BEGIN
--     DELETE FROM STUDENTS WHERE ID = 2;
--     COMMIT;
-- END;


-- BEGIN
--     FOR rec IN (SELECT * FROM GROUPS) LOOP
--         DBMS_OUTPUT.PUT_LINE('Group ID: ' || rec.ID || ', Name: ' || rec.NAME || ', C_VAL: ' || rec.C_VAL);
--     END LOOP;
-- END;
